apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: mkubele/notification:BUILD_VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_PASSWORD
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification