name: Pull Request Check

on:
  pull_request:
    branches: [ master ]

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: assemble ktlint
      - name: Publish reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: '**/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.txt'
          if-no-files-found: ignore
