name: Build master & deploy

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  BUILD_VERSION: 0.0.${{ github.run_number }}

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: ktlint assemble jib -PbuildVersion=${{ env.BUILD_VERSION }}
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Gets K8s context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
        id: login
      - run: |
          sed -i 's/BUILD_VERSION/${{ env.BUILD_VERSION }}/g' k8s/minikube/services/customer/deployment.yml
          sed -i 's/BUILD_VERSION/${{ env.BUILD_VERSION }}/g' k8s/minikube/services/fraud/deployment.yml
          sed -i 's/BUILD_VERSION/${{ env.BUILD_VERSION }}/g' k8s/minikube/services/notification/deployment.yml
      - name: K8s Deploy
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/minikube/bootstrap/rabbitmq/configmap.yml
            k8s/minikube/bootstrap/rabbitmq/rbac.yml
            k8s/minikube/bootstrap/rabbitmq/service.yml
            k8s/minikube/bootstrap/rabbitmq/statefulset.yml
            k8s/minikube/bootstrap/zipkin/service.yml
            k8s/minikube/bootstrap/zipkin/statefulset.yml
            k8s/minikube/services/customer/deployment.yml
            k8s/minikube/services/customer/service.yml
            k8s/minikube/services/fraud/deployment.yml
            k8s/minikube/services/fraud/service.yml
            k8s/minikube/services/notification/deployment.yml
            k8s/minikube/services/notification/service.yml
